# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='active_setup',
            field=models.BooleanField(default=False),
        ),
    ]
