# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='President',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president', to='general.Sister'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='VP_CRS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='VP_CRS', to='general.Sister'),
        ),
    ]
