# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20170613_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='President',
            field=models.ForeignKey(default=1000, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='general.Sister'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='year_of_graduating_seniors',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sister',
            name='class_year',
            field=models.IntegerField(),
        ),
    ]
