# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_sister_prc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sister',
            name='prc',
        ),
        migrations.AddField(
            model_name='sister',
            name='PRC',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sister',
            name='class_year',
            field=models.IntegerField(default=2020),
        ),
    ]
