# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170609_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sister',
            name='class_year',
            field=models.IntegerField(default=0),
        ),
    ]
