# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20170613_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='President',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='president', to='general.Sister'),
        ),
    ]
