# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 20:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20170609_1604'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sister',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
