# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20170613_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='Panhellenic_Delegate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Panhellenic_Delegate', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Facility_Operations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Facility_Operations', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Finance', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Intellectual_Development',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Intellectual_Development', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Membership_Programming',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Membership_Programming', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_New_Member_Ed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_New_Member_Ed', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_PR_and_Marketing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_PR_and_Marketing', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Philanthropy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Philanthropy', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Recruitment', to='general.Sister'),
        ),
        migrations.AddField(
            model_name='setup',
            name='VP_Ritual_and_Fraternity_Appreciation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Ritual_and_Fraternity_Appreciation', to='general.Sister'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='President',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='President', to='general.Sister'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='VP_CRS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_CRS', to='general.Sister'),
        ),
    ]
