# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 09:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20170613_0449'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='VP_Risk_Management',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VP_Risk_Management', to='general.Sister'),
        ),
    ]
