# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_setup_vp_risk_management'),
    ]

    operations = [
        migrations.AddField(
            model_name='sister',
            name='pic',
            field=models.ImageField(default='static/general/images/berd.png', height_field='height', upload_to=b'', width_field='width'),
        ),
    ]
