# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_sister_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='sister',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sister',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default='100', editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sister',
            name='pic',
            field=models.ImageField(default='static/general/images/berd.png', height_field='image_height', upload_to=b'', width_field='image_width'),
        ),
    ]
