# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20170614_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sister',
            name='Profile_image',
            field=models.ImageField(default='/static/general/images/berd.png', height_field='image_height', upload_to=b'', width_field='image_width'),
        ),
    ]
