# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20170614_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sister',
            name='Profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', height_field='image_height', null=True, upload_to='images', width_field='image_width'),
        ),
    ]
