# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-15 00:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0014_auto_20170614_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sister',
            old_name='Profile_image',
            new_name='profile_image',
        ),
    ]
